---
- name: Ensure templates dir
  file:
    path: "{{ install_path }}/templates"
    state: directory
    mode: 0755

- name: Copy repo templates
  copy:
    src: "files/repo"
    dest: "{{ install_path }}/templates/"
    mode: 0644
