---
- name: Install python packages
  apt:
    name:
      - python3
      - python3-pip
      - python-is-python3
      - python3-dev
      - libldap2-dev
      - libsasl2-dev
      - libssl-dev
  become: yes

- name: Install pip python packages
  pip:
    name:
      - python-ldap
      - epdb
      - oci
  become: yes
