---
galaxy_info:
  role_name: adr
  namespace: elhub
  author: elhub/devxp
  description: See README
  company: Elhub
  license: MIT
  min_ansible_version: 2.2
  platforms:
    - name: Ubuntu
      versions:
        - 20.04
  galaxy_tags: []

# Although technically, adr needs neither base or java to install, JAVA_HOME needs to be set in order for the app to
# be able to run.
dependencies:
  - role: base
  - role: java
