---
- name: Upgrade packages
  apt:
    upgrade: yes
    update_cache: yes
  become: yes

- name: Ensure default packages
  package:
    name: "{{ default_packages }}"
    state: present
  become: yes
  retries: 3

- name: Ensure configured packages
  package:
    name: "{{ config_packages }}"
    state: present
  become: yes
  retries: 3
