# hurl tasks
---
- name: Get latest release version from github
  ansible.builtin.uri:
    url: "https://api.github.com/repos/Orange-OpenSource/hurl/releases/latest"
    return_content: yes
  register: _hurl_latest

- name: Register reusable version var
  ansible.builtin.set_fact:
    _hurl_version: "{{ _hurl_latest.json.tag_name }}"

- name: Create lib dir for Hurl
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.local/lib/hurl"
    state: directory
    mode: "0755"

- name: "Download Hurl {{ _hurl_version }}"
  ansible.builtin.unarchive:
    src: "https://github.com/Orange-OpenSource/hurl/releases/download/{{ _hurl_version }}/hurl-{{ _hurl_version }}-x86_64-unknown-linux-gnu.tar.gz"
    remote_src: yes
    dest: "{{ ansible_env.HOME }}/.local/lib/hurl"
    creates: "{{ ansible_env.HOME }}/.local/lib/hurl/hurl-{{ _hurl_version }}-x86_64-unknown-linux-gnu/hurl"

- name: Symlink bin
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.local/bin/hurl"
    src: "{{ ansible_env.HOME }}/.local/lib/hurl/hurl-{{ _hurl_version }}-x86_64-unknown-linux-gnu/hurl"
    state: link
